# Generated by Django 5.1.4 on 2024-12-07 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('frequency', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'locations',
                'unique_together': {('latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=20, unique=True)),
                ('app_shared_count', models.IntegerField(default=0)),
                ('show_app_rating', models.BooleanField(default=False)),
                ('trial_consumed', models.BooleanField(default=False)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('on_ride', models.BooleanField(default=False)),
                ('current_latitude', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('last_active_time', models.DateTimeField(null=True)),
                ('otp', models.CharField(max_length=4)),
                ('razorpay_customer_id', models.CharField(max_length=255, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('total_rides', models.IntegerField(default=0)),
                ('total_ratings', models.IntegerField(default=0)),
                ('referral', models.CharField(max_length=6, unique=True)),
                ('referral_count', models.IntegerField(default=0)),
                ('referral_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('referred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserFavouriteLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('frequency', models.IntegerField(default=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourite_locations', to='users.locations')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourite_locations', to='users.userprofile')),
            ],
            options={
                'db_table': 'user_profile_locations',
            },
        ),
    ]
