# Generated by Django 5.1.4 on 2024-12-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='app_shared_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_longitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_active_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='on_ride',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='razorpay_customer_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='referral',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='referral_amount',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='referral_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='referred_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_app_rating',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_ratings',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_rides',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='trial_consumed',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wallet_balance',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='UserFavouriteLocations',
        ),
    ]
