# Generated by Django 5.1.4 on 2024-12-07 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=20, unique=True)),
                ('show_app_rating', models.BooleanField(default=False)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_latitude', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('last_active_time', models.DateTimeField()),
                ('vehicle_type', models.CharField(max_length=255, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('geohash_code', models.CharField(max_length=12, null=True)),
                ('vehicle', models.CharField(max_length=255, null=True)),
                ('razorpay_customer_id', models.CharField(max_length=255, null=True)),
                ('hatchback_and_sedan', models.BooleanField(default=False)),
                ('insurance_expiry_date', models.DateField(null=True)),
                ('vehicle_license_expiry_date', models.DateField(null=True)),
                ('driving_license_expiry_date', models.DateField(null=True)),
                ('aadhar_number', models.CharField(max_length=255, null=True)),
                ('total_rides', models.IntegerField(default=0)),
                ('total_ratings', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('bank_account_number', models.CharField(max_length=20, null=True)),
                ('ifsc', models.CharField(max_length=20, null=True)),
                ('referral', models.CharField(max_length=6, unique=True)),
                ('referral_count', models.IntegerField(default=0)),
                ('referred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='providers.providerprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider_profile',
            },
        ),
    ]
