# Generated by Django 5.1.4 on 2024-12-09 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='referral',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='referral_count',
        ),
        migrations.RemoveField(
            model_name='providerprofile',
            name='referred_by',
        ),
    ]
