# Generated by Django 5.1.4 on 2024-12-09 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('disco', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='airport_code',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='arrived_at',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='is_airport',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='pink_whip',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='platform_fee',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='provider_profile',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='provider_rating',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='surge',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='toll_amount',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='travel_time_in_mins',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='user_rating',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='waiting_time_in_minutes',
        ),
        migrations.AddField(
            model_name='ride',
            name='available_seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='provider_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), (
                'Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=15),
        ),
        migrations.AddField(
            model_name='ride',
            name='role',
            field=models.CharField(choices=[(
                'Driver', 'Driver'), ('Passenger', 'Passenger')], default='Passenger', max_length=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='estimated_travel_time_in_mins',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='ride',
            table=None,
        ),
    ]
