# Generated by Django 5.1.4 on 2024-12-09 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disco', '0002_remove_ride_airport_code_remove_ride_arrived_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='role',
        ),
    ]
