# Generated by Django 5.1.4 on 2024-12-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disco', '0004_alter_ride_provider_alter_ride_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Waiting', 'Waiting')], default='Scheduled', max_length=15),
        ),
    ]
